server:
  port: 8000
elasticsearch:
  host: localhost
  port: 9200
  clusterName: indexer
  userName:
  password:
  scheme: http
  index: indexer
  type:

dropbox:
  accesskey: DyM650aKB6IAAAAAAAAAAfLhrwNQmgGy4SmGPnqKPFf5JyeAp6EqagvEx449BMVX
  app: testApp

index:
  drivePath: /documents
  localPath: /Users/rahulradhakrishnan/Documents/dropbox